server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  jackson:
    serialization:
      write-dates-as-timestamps: false