spring:
  redis:
    port: 6379
    host: localhost
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true